Repository mindee/doctr-tfjs-demo, pull requests merged in 2021-11, with the labels that each got.

#20 ci: Added CI check to verify installation
  .github/workflows/builds.yml
Labels: enhancement

#21 docs: Added CI badge on README
  .github/workflows/builds.yml
  README.md
Labels: documentation, enhancement

#22 fix: :bug: readme screenshot + typo sidebar
  README.md
  src/components/Sidebar.tsx
Labels: bug

#24 feat: Added Docker deployment option & updated usage instructions
  .dockerignore
  .github/workflows/docker.yml
  Dockerfile
  README.md
Labels: documentation, enhancement

#26 style: Removes unused imports and cleans syntax
  src/components/AnnotationViewer.tsx
  src/components/HeatMap.tsx
  src/components/WordsList.tsx
  src/utils/index.ts
Labels: enhancement

#28 style: Updated favicon, page title & page description
  public/favicon.ico
  public/index.html
  public/manifest.json
Labels: enhancement

#29 docs: Updated README and renamed interface display names
  README.md
  src/components/AnnotationViewer.tsx
  src/components/Sidebar.tsx
  src/components/WordsList.tsx
Labels: documentation, enhancement
